---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: odi-ruby
    run_list:
    - "recipe[user::data_bag]"
    - "recipe[odi-ruby]"
    attributes:
      users:
      - hansolo
      odi-ruby:
        users:
          hansolo:
          - '2.1.2'
          - '1.9.3-p547'
    data_bags_path: test/data_bags
