---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: odi-ruby
    run_list: ["recipe[git]", "recipe[odi-ruby]"]
    attributes: {
      'odi-ruby' => {
        'users' => {
          'vagrant' => [
            '2.1.2',
            '2.1.0',
            '2.0.0-p481',
            '1.9.3-p547'
          ]
        }
      }
    }
    data_bags_path: test/data_bags
