---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: odi-ruby
    run_list: "recipe[odi-ruby]"
    attributes:
    data_bags_path: test/data_bags
